### ISSUE TITLE
Intra processing on CelebA doesn't use any of the algorithms in the initial paper

### ISSUE THREAD

**Issue by HabibAouani** [abacusai/intraprocessing_debiasing#2]
Hello;

Why intra processing of CelebA model doesn't use any of the three algorithms described in the initial paper ? While, the intra processing of tabular data does use all of them.

Is there any matching consideration I didn't understand in the paper ?
Thank you very much !
Habib

**Comment by yashsavani** [comment]
Hi Habib,

Maybe I'm misunderstanding the question, but the three algorithms in the paper are implemented in the intraproc_celeba.py code.

Random: https://github.com/abacusai/intraprocessing_debiasing/blob/main/intraproc_celeba.py#L489
Layerwise Optimization: https://github.com/abacusai/intraprocessing_debiasing/blob/main/intraproc_celeba.py#L525
Adversarial: https://github.com/abacusai/intraprocessing_debiasing/blob/main/intraproc_celeba.py#L571

If you run the following command:
```$ python intraproc_celeba.py config_celeba.yml```
You should get the scores for all the intraprocessing and postprocessing debiasing methods in the `fitz_dark_young.json` file.

Regards,
Yash Savani

**Comment by HabibAouani** [comment]
Hello; 
Thank you very much Yash for your reply !
I got it, I was misled by the absence of the call to the random_perturbation function, in the random.py. It's clear and ok.

The google drive containing the celeba dataset, doesn't allow to download it, hence the command line you put above terminates with error.

```device: cpu
Traceback (most recent call last):
  File "intraproc_celeba.py", line 674, in <module>
    main(yaml_config)
  File "intraproc_celeba.py", line 342, in main
    _, _, _, trainloader, valloader, testloader = load_celeba(
  File "intraproc_celeba.py", line 77, in load_celeba
    trainset = CelebRace(root='./data', download=True, split='train', transform=transform)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/torchvision/datasets/celeba.py", line 74, in __init__
    self.download()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/torchvision/datasets/celeba.py", line 126, in download
    download_file_from_google_drive(file_id, os.path.join(self.root, self.base_folder), filename, md5)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/torchvision/datasets/utils.py", line 164, in download_file_from_google_drive
    raise RuntimeError(msg)
RuntimeError: The daily quota of the file img_align_celeba.zip is exceeded and it can't be downloaded. This is a limitation of Google Drive and can only be overcome by trying again later.

**Comment by yashsavani** [comment]
That error is from the PyTorch code that downloads the CelebA dataset. Unfortunately, there is often high demand for the CelebA dataset and the download fails. I would recommend waiting for a few hours and trying again. Once you are able to download the data you won't have to do it again as subsequent calls will use the previously downloaded version.
